name: Composer validation and unit test execution
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run PHPUnit test suite
      run: composer run-script test
      
    - name: Run Cypress tests on Chrome
      uses: cypress-io/github-action@v5
      timeout-minutes: 10
      with:
        browser: chrome
